### ISSUE TITLE
Bug: Git clone failing - Issue in Filename

### ISSUE THREAD

**Issue by vignesh-murugan-dev** [wasserstoff-india/VisionMark-AI-Assisted-Annotation-Suite#2]
### Bug: Unable to clone the main and forked repositories to local.

**Issue:** Filename "VisionMark: AI-Assisted Annotation Suite.md" is causing the issue due to ":" present in the filename.

**Error:** 
```
error: invalid path 'VisionMark: AI-Assisted Annotation Suite.md'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
```

**Recommended Fix:**
Please remove the ":" in the filename  "VisionMark: AI-Assisted Annotation Suite.md" and rename it to avoid issues.

**Screenshot:**
![Screenshot 2024-04-08 215329](https://github.com/wasserstoff-india/VisionMark-AI-Assisted-Annotation-Suite/assets/108517094/1dcb2263-1f0e-43a5-a315-2209d65ca722)

**Comment by wasserstoff-india** [comment]
Fixed now, try again.

**Comment by vignesh-murugan-dev** [comment]
It works now.

Thanks for fixing it!
